version: '3'
services:
  client:
    build: .
    ports:
      - "8081:80"
    env_file:
      - .env.local
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx.conf.esh:/nginx.conf.esh
#      - ./setup.sh:/setup.sh