name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build, Tag, Publish Docker
        uses: HurricanKai/Publish-Docker-Github-Action@1.12.1
        with:
          name: sureshamk/flux-ui
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: true
          tagging: true